"""PySide6 presentation layer."""

try:  # Generated by pyside6-rcc during Windows build.
    from cnkh_pos import resources_rc as _resources_rc  # noqa: F401
except ImportError:
    _resources_rc = None
